#############################################################################
# Makefile for building: DBtool
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? 10? 23 15:46:43 2019
# Project:  DBtool.pro
# Template: app
# Command: /users/qt/qt_x86/qt485/bin/qmake -spec ../../../qt/qt_x86/qt485/mkspecs/linux-g++ CONFIG+=debug -o Makefile DBtool.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../qt/qt_x86/qt485/mkspecs/linux-g++ -I. -I../../../qt/qt_x86/qt485/include/QtCore -I../../../qt/qt_x86/qt485/include/QtGui -I../../../qt/qt_x86/qt485/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/users/qt/qt_x86/qt485/lib
LIBS          = $(SUBLIBS)  -L/users/qt/qt_x86/qt485//lib -lQtGui -L/users/qt/qt_x86/qt485//lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /users/qt/qt_x86/qt485/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		modelex.cpp moc_mainwindow.cpp \
		qrc_icons.cpp
OBJECTS       = main.o \
		mainwindow.o \
		modelex.o \
		moc_mainwindow.o \
		qrc_icons.o
DIST          = ../../../qt/qt_x86/qt485/mkspecs/common/unix.conf \
		../../../qt/qt_x86/qt485/mkspecs/common/linux.conf \
		../../../qt/qt_x86/qt485/mkspecs/common/gcc-base.conf \
		../../../qt/qt_x86/qt485/mkspecs/common/gcc-base-unix.conf \
		../../../qt/qt_x86/qt485/mkspecs/common/g++-base.conf \
		../../../qt/qt_x86/qt485/mkspecs/common/g++-unix.conf \
		../../../qt/qt_x86/qt485/mkspecs/qconfig.pri \
		../../../qt/qt_x86/qt485/mkspecs/modules/qt_webkit_version.pri \
		../../../qt/qt_x86/qt485/mkspecs/features/qt_functions.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/qt_config.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/exclusive_builds.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/default_pre.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/debug.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/default_post.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/shared.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/warn_on.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/qt.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/unix/thread.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/moc.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/resources.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/uic.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/yacc.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/lex.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/include_source_dir.prf \
		DBtool.pro
QMAKE_TARGET  = DBtool
DESTDIR       = 
TARGET        = DBtool

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: DBtool.pro  ../../../qt/qt_x86/qt485/mkspecs/linux-g++/qmake.conf ../../../qt/qt_x86/qt485/mkspecs/common/unix.conf \
		../../../qt/qt_x86/qt485/mkspecs/common/linux.conf \
		../../../qt/qt_x86/qt485/mkspecs/common/gcc-base.conf \
		../../../qt/qt_x86/qt485/mkspecs/common/gcc-base-unix.conf \
		../../../qt/qt_x86/qt485/mkspecs/common/g++-base.conf \
		../../../qt/qt_x86/qt485/mkspecs/common/g++-unix.conf \
		../../../qt/qt_x86/qt485/mkspecs/qconfig.pri \
		../../../qt/qt_x86/qt485/mkspecs/modules/qt_webkit_version.pri \
		../../../qt/qt_x86/qt485/mkspecs/features/qt_functions.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/qt_config.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/exclusive_builds.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/default_pre.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/debug.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/default_post.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/shared.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/warn_on.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/qt.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/unix/thread.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/moc.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/resources.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/uic.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/yacc.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/lex.prf \
		../../../qt/qt_x86/qt485/mkspecs/features/include_source_dir.prf \
		/users/qt/qt_x86/qt485/lib/libQtGui.prl \
		/users/qt/qt_x86/qt485/lib/libQtCore.prl
	$(QMAKE) -spec ../../../qt/qt_x86/qt485/mkspecs/linux-g++ CONFIG+=debug -o Makefile DBtool.pro
../../../qt/qt_x86/qt485/mkspecs/common/unix.conf:
../../../qt/qt_x86/qt485/mkspecs/common/linux.conf:
../../../qt/qt_x86/qt485/mkspecs/common/gcc-base.conf:
../../../qt/qt_x86/qt485/mkspecs/common/gcc-base-unix.conf:
../../../qt/qt_x86/qt485/mkspecs/common/g++-base.conf:
../../../qt/qt_x86/qt485/mkspecs/common/g++-unix.conf:
../../../qt/qt_x86/qt485/mkspecs/qconfig.pri:
../../../qt/qt_x86/qt485/mkspecs/modules/qt_webkit_version.pri:
../../../qt/qt_x86/qt485/mkspecs/features/qt_functions.prf:
../../../qt/qt_x86/qt485/mkspecs/features/qt_config.prf:
../../../qt/qt_x86/qt485/mkspecs/features/exclusive_builds.prf:
../../../qt/qt_x86/qt485/mkspecs/features/default_pre.prf:
../../../qt/qt_x86/qt485/mkspecs/features/debug.prf:
../../../qt/qt_x86/qt485/mkspecs/features/default_post.prf:
../../../qt/qt_x86/qt485/mkspecs/features/shared.prf:
../../../qt/qt_x86/qt485/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../qt/qt_x86/qt485/mkspecs/features/warn_on.prf:
../../../qt/qt_x86/qt485/mkspecs/features/qt.prf:
../../../qt/qt_x86/qt485/mkspecs/features/unix/thread.prf:
../../../qt/qt_x86/qt485/mkspecs/features/moc.prf:
../../../qt/qt_x86/qt485/mkspecs/features/resources.prf:
../../../qt/qt_x86/qt485/mkspecs/features/uic.prf:
../../../qt/qt_x86/qt485/mkspecs/features/yacc.prf:
../../../qt/qt_x86/qt485/mkspecs/features/lex.prf:
../../../qt/qt_x86/qt485/mkspecs/features/include_source_dir.prf:
/users/qt/qt_x86/qt485/lib/libQtGui.prl:
/users/qt/qt_x86/qt485/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../qt/qt_x86/qt485/mkspecs/linux-g++ CONFIG+=debug -o Makefile DBtool.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/DBtool1.0.0 || $(MKDIR) .tmp/DBtool1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/DBtool1.0.0/ && $(COPY_FILE) --parents mainwindow.h modelex.h .tmp/DBtool1.0.0/ && $(COPY_FILE) --parents icons.qrc .tmp/DBtool1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp modelex.cpp .tmp/DBtool1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/DBtool1.0.0/ && (cd `dirname .tmp/DBtool1.0.0` && $(TAR) DBtool1.0.0.tar DBtool1.0.0 && $(COMPRESS) DBtool1.0.0.tar) && $(MOVE) `dirname .tmp/DBtool1.0.0`/DBtool1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/DBtool1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h
	/users/qt/qt_x86/qt485//bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all: qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp
qrc_icons.cpp: icons.qrc \
		images/about.png \
		images/new.png \
		images/next.png \
		images/exit.png \
		images/copy.png \
		images/cut.png \
		images/redo.png \
		images/save.png \
		images/saveAs.png \
		images/paste.png \
		images/undo.png \
		images/open.png \
		images/previous.png
	/users/qt/qt_x86/qt485/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/users/qt/qt_x86/qt485/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

modelex.o: modelex.cpp modelex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modelex.o modelex.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

